Feat/high light card
bruno-keiko/Restaurant-app pull request #31
Opened 2024-08-15 12:13 UTC by Hudayberdiev2000

2024-08-17 09:52 UTC, bruno-keiko requested changes
Could you use .svg file in next Image instead of creating Icon component

2024-08-19 04:44 UTC, Hudayberdiev2000 commented
i made the change

2024-08-21 07:58 UTC, bruno-keiko commented
> i made the change

Did you forget to push your changes

2024-08-21 08:41 UTC, bruno-keiko requested changes
We need some changes

2024-08-21 08:41 UTC, bruno-keiko commented on src/components/atoms/HighlightCard/HighlightCard.stories.tsx
> +    link: "https://tmcars.info/",
you can replace the link argument with "/"

2024-08-21 08:41 UTC, bruno-keiko commented on src/components/atoms/HighlightCard/HighlightCard.tsx
> +        target="_blank"
We don't need taget='_blank"

2024-08-21 08:41 UTC, bruno-keiko commented on src/components/atoms/HighlightCard/HighlightCard.module.scss
> +      border-radius: 9999px;
You can use br-full variable here

2024-08-21 08:41 UTC, bruno-keiko commented on src/components/atoms/HighlightCard/HighlightCard.module.scss
> +    transition: all 0.3s; /* stylelint-disable-line unit-allowed-list */
Please don't disable any rules.

2024-08-21 09:34 UTC, Hudayberdiev2000 commented
Has made the changes

2024-08-21 09:39 UTC, bruno-keiko requested changes
Please don't change any rules

2024-08-21 09:39 UTC, bruno-keiko commented on .stylelintrc.json
> +    "unit-allowed-list": ["%", "deg", "px", "rem", "ms", "s"],
Don't change rules.

2024-08-21 09:45 UTC, bruno-keiko requested changes
Please revert to unnecessary style changes.

2024-08-21 09:45 UTC, bruno-keiko commented on src/foundations/sass/_colors.scss
> +  --delivery-order-card-color,
Please revert unnecessary style changes. You can use `npm run format:fix` instead of your IDE formatter.

2024-08-21 11:10 UTC, Hudayberdiev2000 commented
resolved the issues

2024-08-24 04:39 UTC, bruno-keiko requested changes

2024-08-24 04:39 UTC, bruno-keiko commented on src/components/atoms/HighlightCard/HighlightCard.module.scss
> +    transition: all #{0.3}s;
Please change it to 300ms

2024-08-26 04:56 UTC, Hudayberdiev2000 commented
I've changed "0.3s" to "300ms"

2024-09-04 06:14 UTC, bruno-keiko requested changes
Could you resolve conflicts by rebasing?

2024-09-04 11:55 UTC, Hudayberdiev2000 commented
I have rebased..

2024-09-05 05:00 UTC, bruno-keiko requested changes
We need to add `primary` and `secondary` modes. Could you look at the design?

2024-09-05 11:32 UTC, Hudayberdiev2000 commented
Did as you asked!

2024-09-06 13:11 UTC, bruno-keiko requested changes
We need minor changes

2024-09-06 13:11 UTC, bruno-keiko commented on src/components/atoms/HighlightCard/HighlightCard.tsx
> +  mode = "secondary",
Please always use "primary" as the default value for clarity.

2024-09-07 05:54 UTC, Hudayberdiev2000 commented
fixed, sorry for silly mistakes:)

2024-09-07 12:07 UTC, bruno-keiko approved these changes

2024-09-07 12:08 UTC, merged