fix(component): centered icon in InfoCard
bruno-keiko/Restaurant-app pull request #33
Opened 2024-08-16 05:13 UTC by Hudayberdiev2000

2024-08-17 10:06 UTC, bruno-keiko requested changes
Please don't use the styling outside of your component.

2024-08-17 10:06 UTC, bruno-keiko commented on src/components/atoms/infoCard/InfoCard.module.scss
> +  svg {
Why do you use an element selector? What do you think if we won't use svg?

2024-08-19 04:30 UTC, Hudayberdiev2000 commented
I made the changes you commented...

2024-08-21 08:23 UTC, bruno-keiko approved these changes

2024-08-21 08:23 UTC, merged