Feat/header #35
bruno-keiko/Restaurant-app pull request #45
Opened 2024-08-23 05:53 UTC by Hudayberdiev2000

2024-08-24 04:32 UTC, bruno-keiko requested changes
This component doesn't seem to match the design.

2024-08-24 04:32 UTC, bruno-keiko commented on src/components/molecules/Header/Header.stories.tsx
> +  // args: {
Please remove unnecessary comments

2024-08-24 04:32 UTC, bruno-keiko commented on src/components/molecules/Header/Header.stories.tsx
> +  title: "Atoms/Header",
Change it to molecules

2024-09-04 05:16 UTC, bruno-keiko requested changes
Good job! We need minor changes

2024-09-04 05:16 UTC, bruno-keiko commented on src/components/molecules/Header/Header.module.scss
> +  box-shadow: 0 5px 5px 0 #0003;
Could you use a variable in colors?

2024-09-04 11:59 UTC, Hudayberdiev2000 commented on src/components/molecules/Header/Header.module.scss
> +  box-shadow: 0 5px 5px 0 #0003;
sure.

2024-09-04 12:30 UTC, Hudayberdiev2000 commented
Has made the change!

2024-09-05 04:54 UTC, merged