feat(component): added SpecialMenu component #38
bruno-keiko/Restaurant-app pull request #51
Opened 2024-09-06 12:20 UTC by Hudayberdiev2000

Fixes #38

2024-09-11 13:06 UTC, bruno-keiko requested changes

2024-09-11 13:06 UTC, bruno-keiko commented on src/components/molecules/SpecialMenu/SpecialMenu.module.scss
> +    & > * {
Why are you using this selector? I haven't seen a need for it. Using this selector causes side effects. One component should not affect the style of other components.

2024-09-14 06:42 UTC, Hudayberdiev2000 commented
bugs are fixed

2024-09-20 12:00 UTC, bruno-keiko requested changes
We have conflicts. Could you resolve it?

2024-09-23 04:52 UTC, merged